### ISSUE TITLE
Elevation data view

### ISSUE THREAD

**Issue by webmap2015** [perliedman/geojson-elevation#2]
Hi,

I want to after right-click and see elevation data like below link?

"https://esri.github.io/esri-leaflet/examples/identifying-imagery.html"

Thanks.

**Comment by perliedman** [comment]
You can look at the [code for the demo app](https://github.com/perliedman/elevation-service/tree/gh-pages), which does more or less this: http://www.liedman.net/elevation-service/

**Comment by webmap2015** [comment]
I'm currently working on a project leaflet.

If possible, can you make it like leaflet plugin?

Thanks.
